### ISSUE TITLE
First prototype

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/Scaling-Ethereum#5]
Create interface sketch

**Comment by lcnwolf** [comment]
👌

**Comment by lcnwolf** [comment]
Here is a clickable prototype of the main page and primary interface: https://www.figma.com/proto/CndVtMgSl7qMzkrT4Et1Lr/Scaling-Ethereum-2023-%E2%9A%A1%EF%B8%8F?page-id=0%3A1&node-id=49-246&starting-point-node-id=49%3A246
