### ISSUE TITLE
1 interface and 2 systems

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/Scaling-Ethereum#6]
Come up with a simple interface suitable to be used with [EIP-2535 multiproxy](https://eips.ethereum.org/EIPS/eip-2535)

- [ ] simple game battle system interface
- [ ] make sure it conforms to registry standards
- [ ] create 2 systems using the interface

**Comment by utgarda** [comment]
https://github.com/chainhackers/diamond-blueprinter/issues/1
